name: Terraform plan

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write   # REQUIRED for OIDC
  contents: read

jobs:
  terraform-plan:
    uses: vallikatakamsetti-crypto/terraform-reusable/.github/workflows/terraform-reusable.yml@main
    with:
      terraform-command: plan
      aws-region: us-east-1
    secrets:
      role-to-assume: ${{ secrets.IAM_GHA_ROLE }}
  



